blog_category:
  type: string
  default: ""
  description:
    en: "Enter the category slug of your blog category as it appears in the url.
      The slug is bold in the following example url:
      https://community.example.org/c/<b>blog-posts</b>/3
      <br><br>
      Note: you may use more than one category slug by comma separating the
      slug values like: <b>blog-one,blog-two</b> <br>
      Be sure there are no spaces after the commas."
blog_tag:
  type: list
  list_type: tag
  default: ""
  description:
    en: "Topics will have blog styling applied when they have any of the tags included in this setting."
image_position:
  type: enum
  default: "below title"
  choices:
    - none
    - above title
    - below title
  description:
    en: "Choose where the featured image appears relative to the title. Only above title will include a summary."
image_size:
  type: enum
  default: "full width"
  choices:
    - full width
    - centered
  description:
    en: "Full width - image spans the full width of the content area.<br>Centered - image maintains its aspect ratio and centers within the content area."
mobile_enabled:
  type: bool
  default: false
  description:
    en: "Enable blog post styling on mobile devices. This uses the default style: full width image, positioned below the title."
